/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PdsButton {
        "accessibleName": string | undefined;
        "block": boolean;
        "disabled": boolean;
        "href": string | undefined;
        "iconOnly": boolean;
        "loading": boolean;
        "rel": string | undefined;
        "size": 'small' | 'medium' | 'large';
        "target": '_blank' | '_parent' | '_self' | '_top';
        "type": 'submit' | 'reset' | 'button';
        "variant": 'primary' | 'secondary' | 'tertiary';
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPdsButtonElement extends Components.PdsButton, HTMLStencilElement {
    }
    var HTMLPdsButtonElement: {
        prototype: HTMLPdsButtonElement;
        new (): HTMLPdsButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "pds-button": HTMLPdsButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PdsButton {
        "accessibleName"?: string | undefined;
        "block"?: boolean;
        "disabled"?: boolean;
        "href"?: string | undefined;
        "iconOnly"?: boolean;
        "loading"?: boolean;
        "rel"?: string | undefined;
        "size"?: 'small' | 'medium' | 'large';
        "target"?: '_blank' | '_parent' | '_self' | '_top';
        "type"?: 'submit' | 'reset' | 'button';
        "variant"?: 'primary' | 'secondary' | 'tertiary';
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "pds-button": PdsButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "pds-button": LocalJSX.PdsButton & JSXBase.HTMLAttributes<HTMLPdsButtonElement>;
        }
    }
}
